FROM alpine:latest

RUN addgroup -g 1001 iperf \
    && adduser -D -u 1001 -G iperf iperf

ENV REMOTE_SITE_HOSTNAME ''
ENV DATADOG_API_KEY ''
ENV DATADOG_APP_KEY ''
ENV JOB_BASE_NAME ''
ENV TEST_DURATION=5

RUN apk upgrade --update --available \
    && apk add \
      bash \
      iperf3 \
      python3 \
      py3-pip \
      git \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && find /var/log -type f | while read f; do echo -ne '' > $f; done;

RUN pip install datadog iperf3
RUN mkdir /etc/iperf3
COPY datadog-iperf.py /etc/iperf3/datadog-iperf.py
RUN chmod 555 /etc/iperf3/datadog-iperf.py

WORKDIR /etc/iperf3/
USER iperf

EXPOSE 5201-5210/udp
EXPOSE 5201-5210/tcp

CMD ["/usr/bin/iperf3", "-s"]

